### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by vapits** [alexurquhart/hugo-geo#5]
Hi there,

thx for the nice template. It's actually my first attempt to use Hugo but I have a problem with the theme (?).

I used another theme and my website was working but after I saw your theme and I simply changed it to yours. From that moment I'm only getting in my site an error:

> 404 page not found

On browser, on devtools no errors. Hugo in the terminal seems to render everything correctly and here is my config file:

``` toml
baseurl = "my-url"
relativeURLs = false
languageCode = "en-us"
title = "My Name"
disqusShortname = "username"
paginate = 5
theme = "hugo-geo"

[taxonomies]
    tag = "tags"

[params]
    # Render the rotating globe in the sidebar
    showglobe = true

    # Google Analytics
    analytics = ""

    # Social buttons for sidebar
    github = "https://github.com/"
    twitter = "https://twitter.com/"
    linkedin = "https://linkedin.com/"

    # Sidebar profile picture
    profilepic = "mypic.jpg"

    # Title/subtitle for the sidebar
    title = "My Name"
    subtitle = "Frontend Developer"

    # Nav links below the profile picture
    [[params.navlinks]]
    name = "About"
    url = "about/"

    [[params.navlinks]]
    name = "Blog"
    url = "posts/"
```

Any ideas?
